# Generated by Django 4.1.3 on 2022-11-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='phone',
            new_name='mobile',
        ),
    ]
