# Generated by Django 4.1.3 on 2022-11-26 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='status',
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.apply')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobseeker')),
            ],
        ),
    ]
